version: "3"

services:
  setup:
    container_name: setup
    build:
      context: ./setup
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      GIN_MODE: release

  authentication:
    container_name: authentication
    build:
      context: ./authentication
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      GIN_MODE: release

  transaction:
    container_name: transaction
    build:
      context: ./transaction
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      GIN_MODE: release

  frontend:
    container_name: frontend
    build:
      context: ./client/app
    ports:
      - "80:3000"

  database:
    container_name: database
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: db123
      POSTGRES_USER: nt_user
      POSTGRES_DB: nt_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8181:8181"
