version: "3"

services:
  setup:
    container_name: setup
    build:
      context: ./setup
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      GIN_MODE: release

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      GIN_MODE: release
