name: Tester

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d database authentication transaction setup engine jmeter

      - name: Wait for results.jtl
        run: |
          while [ ! -s ./tests/results.jtl ]; do sleep 5; done

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: "./tests/results.jtl"
